#!/bin/sh 

sbt_path=`which sbt`
if [ "`which sbt`" == "" ]; then
  brew install sbt
fi

function run_app() {
  sbt "project example" "~;container:restart"
}

command="$1"
if [ "$command" == "run" ];then
  run_app
elif [ "$command" == "clean" ];then
  sbt clean
elif [ "$command" == "update" ];then
  sbt update
elif [ "$command" == "console" ];then
  sbt example/console
elif [ "$command" == "compile" ];then
  sbt compile
elif [ "$command" == "example-test" ];then
  export SKINNY_ENV=test
  sbt example/test
elif [ "$command" == "test" ];then
  export SKINNY_ENV=test
  sbt test
elif [ "$command" == "db:migrate" ];then
  sbt "example/run db:migrate $2"
elif [ "$command" == "package" ];then
  sbt package
else
  echo ""
  echo "Usage: skinny [COMMAND] [OPTIONS]..."
  echo ""
  echo "  run       : will run example app"
  echo "  clean     : will clear target directory"
  echo "  update    : will update dependencies"
  echo "  console   : will run sbt console"
  echo "  compile   : will compile all the classes"
  echo "  test      : will run all the tests"
  echo "  package   : will create *.war file to deploy"
  echo ""
fi


