#!/bin/sh 

sbt_path=`which sbt`
if [ "`which sbt`" == "" ]; then
  brew install sbt
fi

function run_app() {
  sbt "~;container:stop;container:start"
}

command="$1"
if [ $command == "run" ];then
  run_app
elif [ $command == "clean" ];then
  sbt clean
elif [ $command == "update" ];then
  sbt update
elif [ $command == "console" ];then
  sbt console
elif [ $command == "compile" ];then
  sbt compile
elif [ $command == "test" ];then
  sbt test
elif [ $command == "test-only" ];then
  sbt "test-only $2"
elif [ $command == "package" ];then
  sbt package
else
  echo ""
  echo "Usage: skinny [COMMAND] [OPTIONS]..."
  echo ""
  echo "  run       : will run Skinny app for local development"
  echo "  clean     : will clear target directory"
  echo "  update    : will update dependencies"
  echo "  console   : will run sbt console"
  echo "  compile   : will compile all the classes"
  echo "  test      : will run all the tests"
  echo "  test-only : will run the specified test"
  echo "  package   : will create *.war file to deploy"
  echo ""
fi


