#!/bin/sh
SBT_OPTS="-XX:MaxPermSize=256M"
test -f $HOME/.sbtconfig && . $HOME/.sbtconfig
cd `dirname $0`
current_dir=`pwd`
exec java -Xmx1024M ${SBT_OPTS} -jar ${current_dir}/bin/sbt-launch.jar "$@"

